"""
Data necessary for the correct functioning of the program
"""

API_TEQUILA = "YOU APIKEY FROM TEQUILA"
AUTH_BEARER = "AUTH BEARER FROM SHEETY"
SHEETY_ENDPOINT = "YOUR SHEETY ENDPOINT"
BASE_URL = "YOUR BASE URL FROM SHEET"
API_EXCHANGE_RATE = "YOUR API EXCHANGE RATE"
TWILIO_PHONE = "YOUR TWILIO PHONE"
ACCOUNT_SID = "YOUR ACCOUNT SID FROM TWILIO"
AUTH_TOKEN = "YOUR TOKEN AUTH FROM TWILIO"
PHONE = "PHONE DESTINATION"